### ISSUE TITLE
Problems installing llama2 (failure building wheel)

### ISSUE THREAD

**Issue by wanyingtian** [thisserand/llama2_local#12]
Hello, 

I am having problems installing Llama2. I am trying to install it on Windows and I am stuck on the step where you run:
`pip install -r requirements.txt `

**_Note: I made sure to have CMake, MinGW64, VS, and VS Build Tools installed and also have the environment variables including file paths to MingGW/bin and CMake/bin._**

I get the following failure:

`Building wheel for llama-cpp-python (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for llama-cpp-python (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [199 lines of output]

      --------------------------------------------------------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- The C compiler identification is GNU 11.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/mingw64/bin/gcc.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is GNU 11.2.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/mingw64/bin/c++.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:9 (message):
        MSVC is required to pass this check.

      -- Configuring incomplete, errors occurred!
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Ninja (Visual Studio 17 2022 x64 v143)' generator - failure
      --------------------------------------------------------------------------------

      --------------------------------------------------------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator
      --------------------------------
      ---------------------------
      ----------------------
      -----------------
      ------------
      -------
      --
      Not searching for unused variables given on the command line.
      CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
      -- The C compiler identification is MSVC 19.37.32824.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- The CXX compiler identification is MSVC 19.37.32824.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Configuring done (18.0s)
      -- Generating done (0.0s)
      -- Build files have been written to: C:/Users/wanyi/AppData/Local/Temp/pip-install-74r1bdtd/llama-cpp-python_5cf10169b309419697c9247200f9fe90/_cmake_test_compile/build
      --
      -------
      ------------
      -----------------
      ----------------------
      ---------------------------
      --------------------------------
      -- Trying 'Visual Studio 17 2022 x64 v143' generator - success
      --------------------------------------------------------------------------------

      Configuring Project
        Working directory:
          C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build
        Command:
          'C:\Users\wanyi\AppData\Local\Temp\pip-build-env-7s_z186d\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90' -G 'Visual Studio 17 2022' --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.10.9 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\wanyi\AppData\Local\Temp\pip-build-env-7s_z186d\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPython_EXECUTABLE:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\Include' '-DPython_LIBRARY:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPython3_EXECUTABLE:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\Include' '-DPython3_LIBRARY:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\libs\python310.lib' -T v143 -A x64 -DCMAKE_BUILD_TYPE:STRING=Release

      Not searching for unused variables given on the command line.
      -- Selecting Windows SDK version 10.0.22000.0 to target Windows 10.0.22621.
      -- The C compiler identification is MSVC 19.37.32824.0
      -- The CXX compiler identification is MSVC 19.37.32824.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - failed
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe - broken
      CMake Error at C:/Users/wanyi/AppData/Local/Temp/pip-build-env-7s_z186d/overlay/Lib/site-packages/cmake/data/share/cmake-3.27/Modules/CMakeTestCCompiler.cmake:67 (message):
        The C compiler

          "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/VC/Tools/MSVC/14.37.32822/bin/Hostx64/x64/cl.exe"

        is not able to compile a simple test program.

        It fails with the following output:

          Change Dir: 'C:/Users/wanyi/AppData/Local/Temp/pip-install-74r1bdtd/llama-cpp-python_5cf10169b309419697c9247200f9fe90/_skbuild/win-amd64-3.10/cmake-build/CMakeFiles/CMakeScratch/TryCompile-68uuwd'

          Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2022/BuildTools/MSBuild/Current/Bin/amd64/MSBuild.exe" cmTC_09e2c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n
          MSBuild version 17.7.2+d6990bcfa for .NET Framework
          Build started 2023-09-17 2:37:44 PM.

          Project "C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj" on node 1 (default targets).
          PrepareForBuild:
            Creating directory "cmTC_09e2c.dir\Debug\".
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
            Creating directory "C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\Debug\".
            Creating directory "cmTC_09e2c.dir\Debug\cmTC_09e2c.tlog\".
          InitializeBuildStatus:
            Creating "cmTC_09e2c.dir\Debug\cmTC_09e2c.tlog\unsuccessfulbuild" because "AlwaysCreate" was specified.
            Touching "cmTC_09e2c.dir\Debug\cmTC_09e2c.tlog\unsuccessfulbuild".
          ClCompile:
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\VC\Tools\MSVC\14.37.32822\bin\HostX64\x64\CL.exe /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_09e2c.dir\Debug\\" /Fd"cmTC_09e2c.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\testCCompiler.c"
            Microsoft (R) C/C++ Optimizing Compiler Version 19.37.32824 for x64
            Copyright (C) Microsoft Corporation.  All rights reserved.
            testCCompiler.c
            cl /c /Zi /W1 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\"Debug\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_09e2c.dir\Debug\\" /Fd"cmTC_09e2c.dir\Debug\vc143.pdb" /external:W1 /Gd /TC /errorReport:queue "C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\testCCompiler.c"
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.dir\Debug\cmTC_09e2c.tlog'. [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          Done Building Project "C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj" (default targets) -- FAILED.

          Build FAILED.

          "C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj" (default target) (1) ->
          (PrepareForBuild target) ->
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppBuild.targets(541,5): warning MSB8029: The Intermediate directory or Output directory cannot reside under the Temporary directory as it could lead to issues with incremental build. [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]

          "C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj" (default target) (1) ->
          (ClCompile target) ->
            C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003: The specified task executable "CL.exe" could not be run. System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.dir\Debug\cmTC_09e2c.tlog'. [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1.CommonInit() [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at System.IO.Directory.GetFiles(String path, String searchPattern) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.Utilities.TrackedDependencies.ExpandWildcards(ITaskItem[] expand) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.Utilities.CanonicalTrackedOutputFiles.InternalConstruct(ITask ownerTask, ITaskItem[] tlogFiles, Boolean constructOutputsFromTLogs) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.CPPTasks.CL.PostExecuteTool(Int32 exitCode) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.CPPTasks.TrackedVCToolTask.ExecuteTool(String pathToTool, String responseFileCommands, String commandLineCommands) [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]
          C:\Program Files (x86)\Microsoft Visual Studio\2022\BuildTools\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(741,5): error MSB6003:    at Microsoft.Build.Utilities.ToolTask.Execute() [C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build\CMakeFiles\CMakeScratch\TryCompile-68uuwd\cmTC_09e2c.vcxproj]

              1 Warning(s)
              1 Error(s)

          Time Elapsed 00:00:01.76

        CMake will not be able to correctly generate this project.
      Call Stack (most recent call first):
        CMakeLists.txt:3 (project)

      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Users\wanyi\AppData\Local\Temp\pip-build-env-7s_z186d\overlay\Lib\site-packages\skbuild\setuptools_wrap.py", line 666, in setup
          env = cmkr.configure(
        File "C:\Users\wanyi\AppData\Local\Temp\pip-build-env-7s_z186d\overlay\Lib\site-packages\skbuild\cmaker.py", line 357, in configure
          raise SKBuildError(msg)

      An error occurred while configuring with CMake.
        Command:
          'C:\Users\wanyi\AppData\Local\Temp\pip-build-env-7s_z186d\overlay\Lib\site-packages\cmake\data\bin/cmake.exe' 'C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90' -G 'Visual Studio 17 2022' --no-warn-unused-cli '-DCMAKE_INSTALL_PREFIX:PATH=C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-install' -DPYTHON_VERSION_STRING:STRING=3.10.9 -DSKBUILD:INTERNAL=TRUE '-DCMAKE_MODULE_PATH:PATH=C:\Users\wanyi\AppData\Local\Temp\pip-build-env-7s_z186d\overlay\Lib\site-packages\skbuild\resources\cmake' '-DPYTHON_EXECUTABLE:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\python.exe' '-DPYTHON_INCLUDE_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\Include' '-DPYTHON_LIBRARY:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPython_EXECUTABLE:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\python.exe' '-DPython_ROOT_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310' -DPython_FIND_REGISTRY:STRING=NEVER '-DPython_INCLUDE_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\Include' '-DPython_LIBRARY:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\libs\python310.lib' '-DPython3_EXECUTABLE:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\python.exe' '-DPython3_ROOT_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310' -DPython3_FIND_REGISTRY:STRING=NEVER '-DPython3_INCLUDE_DIR:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\Include' '-DPython3_LIBRARY:PATH=C:\Users\wanyi\AppData\Local\Programs\Python\Python310\libs\python310.lib' -T v143 -A x64 -DCMAKE_BUILD_TYPE:STRING=Release
        Source directory:
          C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90
        Working directory:
          C:\Users\wanyi\AppData\Local\Temp\pip-install-74r1bdtd\llama-cpp-python_5cf10169b309419697c9247200f9fe90\_skbuild\win-amd64-3.10\cmake-build
      Please see CMake's output for more information.

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for llama-cpp-python
Failed to build llama-cpp-python
ERROR: Could not build wheels for llama-cpp-python, which is required to install pyproject.toml-based projects`

Any help or suggestions would be highly appreciated! 

Thanks!

**Comment by LittleM-fun-code** [comment]
same issue
