### ISSUE TITLE
ValueError: Need either a `state_dict` or a `save_folder` containing offloaded weights.

### ISSUE THREAD

**Issue by prameelareddi** [thisserand/llama2_local#8]
python llama.py --model_name="meta-llama/Llama-2-7b-hf"

Downloading (…)lve/main/config.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 609/609 [00:00<00:00, 1.98MB/s]
Downloading (…)fetensors.index.json: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26.8k/26.8k [00:00<00:00, 56.4MB/s]
Downloading (…)of-00002.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 9.98G/9.98G [07:43<00:00, 21.5MB/s]
Downloading (…)of-00002.safetensors: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 3.50G/3.50G [02:43<00:00, 21.4MB/s]
Downloading shards: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [10:29<00:00, 314.61s/it]
Loading checkpoint shards: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:07<00:00,  3.75s/it]
Downloading (…)neration_config.json: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 167/167 [00:00<00:00, 756kB/s]
Traceback (most recent call last):
  File "/home/prameela/PycharmProjects/llama_local/llama2_local/llama.py", line 114, in <module>
    fire.Fire(main)
  File "/home/prameela/anaconda3/envs/llama_local/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prameela/anaconda3/envs/llama_local/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/home/prameela/anaconda3/envs/llama_local/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prameela/PycharmProjects/llama_local/llama2_local/llama.py", line 110, in main
    model, tokenizer = init_auto_model_and_tokenizer(model_name, model_type, file_name)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prameela/PycharmProjects/llama_local/llama2_local/llama.py", line 55, in init_auto_model_and_tokenizer
    model, tokenizer = initialize_gpu_model_and_tokenizer(model_name, model_type=model_type)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prameela/PycharmProjects/llama_local/llama2_local/llama.py", line 40, in initialize_gpu_model_and_tokenizer
    model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", token=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prameela/anaconda3/envs/llama_local/lib/python3.11/site-packages/transformers/models/auto/auto_factory.py", line 493, in from_pretrained
    return model_class.from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prameela/anaconda3/envs/llama_local/lib/python3.11/site-packages/transformers/modeling_utils.py", line 2959, in from_pretrained
    dispatch_model(model, **kwargs)
  File "/home/prameela/anaconda3/envs/llama_local/lib/python3.11/site-packages/accelerate/big_modeling.py", line 364, in dispatch_model
    weights_map = OffloadedWeightsLoader(
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/prameela/anaconda3/envs/llama_local/lib/python3.11/site-packages/accelerate/utils/offload.py", line 150, in __init__
    raise ValueError("Need either a `state_dict` or a `save_folder` containing offloaded weights.")
ValueError: Need either a `state_dict` or a `save_folder` containing offloaded weights.

**Comment by unmeshk75** [comment]
Hi! 
Has anyone found a resolution to this problem? I am able to run the models on local Linux laptop, but on Windows it's giving me this specific error.

**Comment by ShanLorde** [comment]
I'm getting the same ValueError on my M2 mac.
